on:
  push:
    branches:
      - master1








jobs:
  build:
    runs-on: ubuntu-latest
      

    steps: 
      - name: 'test action'
        run: pwd

      - name: 'test action1'
        run: echo 'manar zain'

      - name: 'before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'after'
        run: ls

      - name: "login docker hub"
        run: docker login --username manarzain --password dckr_pat_rphv7tajg4XpAoAsxDNwxi6-FCA